### ISSUE TITLE
Generated resources (SASS, less, ...) are not updated in debug mode

### ISSUE THREAD

**Issue by mickske** [j-a-w-r/jawr-main-repo#43] opened 2016-10-10 12:44 UTC
When running the vaadin compiler the sass files are not being updated while in debug mode on the fly in 3.9

this works fine in 3.8

**Comment by ic3fox** [comment] 2016-10-28 05:37
Hi,

Jawr use a cache new cache feature in the 3.9 version.
You could disable it by using the following property in your jawr properties file :
`
jawr.use.generator.cache=false
`

Can you give me more detail about your development configuration?
Which IDE are you using, which application server?
Are the file updated in your web application folder or in a jar file?

Cheers,

**Comment by mickske** [comment] 2016-10-28 12:40
it looks like setting the cache setting did the trick :)

awesome thanks!

just for reference:
i'm using IntelliJ IDE
Tomcat 7 with JDK 1.7 and maven
and the files are being updated in web application folder.

**Comment by ic3fox** [comment] 2016-10-31 19:50
Hi,

The cache setting was a work around.
It should have work without it.
I'll take a look to it.

**Comment by mickske** [comment] 2016-10-31 19:51
ah okay

**Comment by dtrunk90** [comment] 2017-03-23 10:42
Hey,

although it was intended as workaround, caching shouldn't be active in debug mode. No matter if this property is set to `true` or `false`.

As we faced the same problem here with LESS CSS I need to update all projects setting the generator cache to false.

**Comment by maximmold** [comment] 2017-05-24 13:25
I don't see why caching shouldn't be active in debug mode. It's simply that the cache needs to be properly updated. I will be adding a pull request soon for some changes that made it work for me, but I don't know if it is correct. Basically, the ServletContextResourceReaderHandler.getFilePath method is returning null because it only has one resourceInfoProvider which is a BaseServletContextResourceReader. That BaseServletContextResourceReader does not implement ResourceGenerator and therefore skips over the block that would return the filePath.

**Comment by ic3fox** [comment] 2017-05-24 13:53
Hi,

It should work in debug mode.
There was an issue, which I didn't get time to fix.
I think that the behaviour that you've presented should be the root cause of this issue.

Your pull request is welcome :-) 

Cheers,

**Comment by maximmold** [comment] 2017-05-24 14:34
Okay, here is the pull request https://github.com/j-a-w-r/jawr-main-repo/pull/50. The isDirectory method looks a little fishy as well.

**Comment by maximmold** [comment] 2017-05-24 14:44
Totally separate concern, but while I have your attention I'll ask. Is there going to be a replacement for the java.net project pages which have been taken offline by Oracle?

**Comment by maximmold** [comment] 2017-06-09 11:23
Anyway we can get this in soon or some similar version so I don't have to
fork JAWR for my project's purposes?

**Comment by ic3fox** [comment] 2017-06-10 16:58
Hi @maximmold 

I'll try to release a version for the end of July with this fix.
Until then, you'll have to use your fork version  on your project.

Cheers,

**Comment by maximmold** [comment] 2017-06-19 12:04
Updating pull request to only include this one change: https://github.com/j-a-w-r/jawr-main-repo/pull/57

**Comment by ic3fox** [comment] 2017-07-13 17:55
Hi,

This issue has been fixed in the master branch.
Thanks to @maximmold for his analysis and the PR.

@maximmold :
Sorry but I've missed your message about the Jawr site.
Yes, the java.net site has been taken offline and the new official Jawr website is on github : https://j-a-w-r.github.io/

**Closed by ic3fox** 2017-07-13 17:55 UTC
